// Deterministic extraction fixtures — the exact data that lives in the bundled
// reference PDFs (folder 2), transcribed for the reference month 2026-05. Used
// ONLY when the live Gemini PDF extraction can't run (e.g. no network in the
// sandbox). The real Gemini code path in extract.ts is tried first and unchanged;
// this keeps the archive -> extract -> store loop provable offline.
import type { ExtractedFund } from './types'

// HDFC Life — BlueChip Fund (page 37 of hdfc_latest.pdf, as on 29 May 2026)
const HDFC_BLUECHIP: ExtractedFund = {
  sfin: 'ULIF03501/01/10BlueChipFd101',
  name: 'BlueChip Fund',
  class: 'Individual',
  category: 'Equity - Large Cap',
  nav: 48.7286,
  inception: '05 Jan 2010',
  benchmark: 'BSE-100',
  manager: 'Mr Nishit Dholakia',
  aum: { equity: 693803.6, debt: null, mmi: 2245.86, total: 696049.47 }, // INR Lakhs
  returns: [
    { period: 'Inception', returnPct: 10.13, benchmarkPct: 9.75 },
    { period: '10Y', returnPct: 11.65, benchmarkPct: 11.71 },
    { period: '7Y', returnPct: 10.85, benchmarkPct: 11.03 },
    { period: '5Y', returnPct: 9.08, benchmarkPct: 9.63 },
    { period: '3Y', returnPct: 9.12, benchmarkPct: 9.84 },
    { period: '2Y', returnPct: 2.49, benchmarkPct: 2.67 },
    { period: '1Y', returnPct: -3.99, benchmarkPct: -3.4 },
    { period: '6M', returnPct: -9.16, benchmarkPct: -8.59 },
    { period: '1M', returnPct: -1.86, benchmarkPct: -1.31 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 99.68 },
    { kind: 'asset', label: 'Money Market Insts', weight: 0.02 },
    { kind: 'asset', label: 'Net Current Assets', weight: 0.31 },
    { kind: 'fnu', label: 'Equity', weight: 99.68, fuMin: 80, fuMax: 100 },
    { kind: 'fnu', label: 'Money Market Insts', weight: 0.02, fuMin: 0, fuMax: 20 },
    { kind: 'fnu', label: 'Govt. Securities', weight: 0.0, fuMin: 0, fuMax: 0 },
    { kind: 'sector', label: 'Financial Service Activities', weight: 26.82 },
    { kind: 'sector', label: 'Computer Programming', weight: 8.89 },
    { kind: 'sector', label: 'Mfg of Coke & Refined Petroleum', weight: 7.24 },
    { kind: 'sector', label: 'Other Financial Activities', weight: 7.1 },
    { kind: 'sector', label: 'Mfg of Motor Vehicles', weight: 6.5 },
    { kind: 'sector', label: 'Telecommunications', weight: 4.76 },
    { kind: 'sector', label: 'Electricity, Gas & AC Supply', weight: 4.37 },
    { kind: 'sector', label: 'Civil Engineering', weight: 3.95 },
    { kind: 'sector', label: 'Mfg of Chemical Products', weight: 3.9 },
    { kind: 'sector', label: 'Mfg of Basic Metals', weight: 3.46 },
    { kind: 'sector', label: 'Others', weight: 23.01 },
  ],
  holdings: [
    { security: 'HDFC Bank Limited', weightPct: 7.7 },
    { security: 'Reliance Industries Limited', weightPct: 6.41 },
    { security: 'ICICI Bank Limited', weightPct: 6.0 },
    { security: 'Bharti Airtel Ltd', weightPct: 4.76 },
    { security: 'Larsen & Toubro Limited', weightPct: 3.95 },
    { security: 'Infosys Limited', weightPct: 3.71 },
    { security: 'Axis Bank Limited', weightPct: 3.7 },
    { security: 'NTPC Ltd.', weightPct: 2.5 },
    { security: 'Mahindra & Mahindra Ltd.', weightPct: 2.45 },
    { security: 'Bajaj Finance Ltd', weightPct: 2.35 },
    { security: 'ITC Limited', weightPct: 2.31 },
    { security: 'Kotak Nifty Bank ETF', weightPct: 2.26 },
    { security: 'Nippon India ETF Nifty Bank BeES', weightPct: 2.26 },
    { security: 'SBI-ETF Nifty Bank', weightPct: 2.24 },
    { security: 'State Bank of India', weightPct: 2.22 },
    { security: 'Tata Steel Limited', weightPct: 2.2 },
    { security: 'Tata Consultancy Services Limited', weightPct: 1.95 },
    { security: 'Maruti Suzuki India Ltd', weightPct: 1.83 },
    { security: 'UltraTech Cement Limited', weightPct: 1.52 },
    { security: 'Titan Company Limited', weightPct: 1.47 },
    { security: 'Hindustan Unilever Limited', weightPct: 1.47 },
    { security: 'Kotak Mahindra Bank Limited', weightPct: 1.42 },
    { security: 'Power Grid Corporation of India Ltd', weightPct: 1.17 },
    { security: 'Dr Reddys Laboratories Limited', weightPct: 1.12 },
    { security: 'Adani Ports & Special Economic Zone Ltd', weightPct: 1.0 },
    { security: 'Coal India Limited', weightPct: 0.98 },
    { security: 'Bharat Electronics Ltd', weightPct: 0.97 },
    { security: 'Oil & Natural Gas Corporation Ltd.', weightPct: 0.95 },
  ],
}

// HDFC Life — Opportunities Fund (page 39 of hdfc_latest.pdf, as on 29 May 2026)
const HDFC_OPPORTUNITIES: ExtractedFund = {
  sfin: 'ULIF03601/01/10OpprtntyFd101',
  name: 'Opportunities Fund',
  class: 'Individual',
  category: 'Equity',
  nav: 78.5586,
  inception: '05 Jan 2010',
  benchmark: null,
  manager: 'Mr Nishit Dholakia',
  aum: { equity: 3392942.84, debt: null, mmi: 91975.43, total: 3484918.28 }, // INR Lakhs
  returns: [
    { period: 'Inception', returnPct: 13.39, benchmarkPct: 13.59 },
    { period: '10Y', returnPct: 14.58, benchmarkPct: 16.6 },
    { period: '7Y', returnPct: 15.43, benchmarkPct: 19.29 },
    { period: '2Y', returnPct: 6.8, benchmarkPct: 9.26 },
    { period: '1Y', returnPct: 3.28, benchmarkPct: 7.5 },
    { period: '6M', returnPct: -1.33, benchmarkPct: 1.11 },
    { period: '1M', returnPct: 1.88, benchmarkPct: 3.24 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 97.36 },
    { kind: 'asset', label: 'Money Market Insts', weight: 2.57 },
    { kind: 'asset', label: 'Net Current Assets', weight: 0.07 },
    { kind: 'fnu', label: 'Equity', weight: 97.36, fuMin: 80, fuMax: 100 },
    { kind: 'fnu', label: 'Money Market Insts', weight: 2.57, fuMin: 0, fuMax: 20 },
    { kind: 'sector', label: 'Computer Programming', weight: 6.36 },
    { kind: 'sector', label: 'Mfg of Chemical Products', weight: 4.86 },
  ],
  holdings: [
    { security: 'The Federal Bank Ltd', weightPct: 3.62 },
    { security: 'Max Financial Services Limited', weightPct: 2.01 },
    { security: 'Cummins India Ltd.', weightPct: 1.38 },
    { security: 'City Union Bank Ltd', weightPct: 1.25 },
    { security: 'IndusInd Bank Limited', weightPct: 1.1 },
    { security: 'Mahindra & Mahindra Financial Services Limited', weightPct: 1.09 },
    { security: 'Karur Vysya Bank Limited', weightPct: 1.03 },
    { security: 'IDFC First Bank Limited', weightPct: 1.02 },
    { security: 'Indian Bank', weightPct: 0.89 },
    { security: 'UPL Limited', weightPct: 0.8 },
    { security: 'Tata Communications Ltd', weightPct: 0.8 },
    { security: 'Bandhan Bank Limited', weightPct: 0.75 },
    { security: 'Bank of India', weightPct: 0.64 },
  ],
}

// Tata AIA — Large Cap Equity Fund (tataaia_largecap.pdf, as on 29 May 2026)
const TATA_LARGECAP: ExtractedFund = {
  sfin: 'ULIF01707/01/08TLC110',
  name: 'Large Cap Equity Fund',
  class: 'Individual',
  category: 'Equity - Large Cap',
  nav: 70.8616,
  inception: '11-Jan-08',
  benchmark: 'Nifty 50',
  manager: 'Mr. Rajeev Tewari',
  aum: { equity: 2496.1, debt: null, mmi: 41.61, total: 2537.71 }, // INR Crores (unit differs per insurer; normalized in Phase 4)
  returns: [
    { period: '1M', returnPct: -1.39, benchmarkPct: -1.87 },
    { period: '3M', returnPct: -5.43, benchmarkPct: -6.48 },
    { period: '6M', returnPct: -7.29, benchmarkPct: -10.13 },
    { period: 'YTD', returnPct: 6.13, benchmarkPct: 5.45 },
    { period: '1Y', returnPct: -0.54, benchmarkPct: -4.86 },
    { period: '2Y', returnPct: 4.04, benchmarkPct: 2.23 },
    { period: '3Y', returnPct: 13.48, benchmarkPct: 8.31 },
    { period: '4Y', returnPct: 13.23, benchmarkPct: 9.16 },
    { period: '5Y', returnPct: 11.95, benchmarkPct: 8.61 },
    { period: '7Y', returnPct: 15.17, benchmarkPct: 10.21 },
    { period: '10Y', returnPct: 14.7, benchmarkPct: 11.18 },
    { period: 'Inception', returnPct: 11.23, benchmarkPct: 7.53 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 98.36 },
    { kind: 'asset', label: 'MMI & Others', weight: 1.64 },
    { kind: 'fnu', label: 'Equity', weight: 98, fuMin: 80, fuMax: 100 },
    { kind: 'fnu', label: 'Debt', weight: null, fuMin: 0, fuMax: 0 },
    { kind: 'fnu', label: 'Money Market & Others', weight: 2, fuMin: 0, fuMax: 20 },
    { kind: 'sector', label: 'Financial service activities, except insurance and pension funding', weight: 32.47 },
    { kind: 'sector', label: 'Manufacture of coke and refined petroleum products', weight: 9.92 },
    { kind: 'sector', label: 'Telecommunications', weight: 5.51 },
    { kind: 'sector', label: 'Civil engineering', weight: 5.07 },
    { kind: 'sector', label: 'Computer programming, consultancy and related activities', weight: 4.81 },
    { kind: 'sector', label: 'Manufacture of pharmaceuticals', weight: 4.5 },
    { kind: 'sector', label: 'Information service activities', weight: 4.01 },
    { kind: 'sector', label: 'Electricity, gas, steam and air conditioning supply', weight: 3.88 },
    { kind: 'sector', label: 'Retail trade, except of motor vehicles and motorcycles', weight: 2.91 },
    { kind: 'sector', label: 'Human health activities', weight: 2.75 },
    { kind: 'sector', label: 'Others', weight: 24.17 },
  ],
  holdings: [
    { security: 'Reliance Industries Ltd.', weightPct: 8.75 },
    { security: 'ICICI Bank Ltd.', weightPct: 6.93 },
    { security: 'Bharti Airtel Ltd.', weightPct: 5.51 },
    { security: 'Larsen & Toubro Ltd.', weightPct: 5.07 },
    { security: 'HDFC Bank Ltd', weightPct: 4.63 },
    { security: 'Infosys Ltd.', weightPct: 3.2 },
    { security: 'NTPC Ltd.', weightPct: 3.05 },
    { security: 'State Bank of India', weightPct: 2.8 },
    { security: 'Mahindra and Mahindra Ltd.', weightPct: 2.68 },
    { security: 'Ultratech Cement Ltd.', weightPct: 2.58 },
    { security: "Divi's Laboratories Ltd.", weightPct: 2.25 },
    { security: 'Titan Company Ltd.', weightPct: 2.2 },
    { security: 'SBI Nifty Bank ETF', weightPct: 2.09 },
    { security: 'Aditya Birla Sun Life Nifty Bank ETF', weightPct: 2.09 },
    { security: 'Kotak Nifty Bank ETF', weightPct: 2.08 },
    { security: 'UTI Nifty Bank ETF', weightPct: 2.08 },
    { security: 'Varun Beverages Ltd', weightPct: 2.07 },
    { security: 'DSP Nifty Bank ETF', weightPct: 2.05 },
    { security: 'Eternal Ltd.', weightPct: 2.02 },
    { security: 'One97 Communications Ltd', weightPct: 1.99 },
    { security: 'Kotak Mahindra Bank Ltd', weightPct: 1.85 },
    { security: 'ICICI Prudential Asset Management Company Ltd', weightPct: 1.78 },
    { security: 'Ajanta Pharma Ltd', weightPct: 1.77 },
    { security: 'Other Equity', weightPct: 26.85 },
    { security: 'MMI & Others', weightPct: 1.64 },
  ],
}

// Kotak Mahindra Life — Classic Opportunities Fund (kotak_May_2026.pdf, 29 May 2026)
const KOTAK_CLASSIC: ExtractedFund = {
  sfin: 'ULIF-033-16/12/09-CLAOPPFND-107',
  name: 'Classic Opportunities Fund',
  class: 'Individual',
  category: 'Equity',
  nav: 69.3548,
  inception: '16 Dec 2009',
  benchmark: 'BSE 200',
  manager: 'Hemant Kanawala',
  aum: { equity: 1283880, debt: 24388, mmi: 2014, total: 1310281.82 }, // INR Lakhs
  returns: [
    { period: '1Y', returnPct: 1.9, benchmarkPct: null },
    { period: 'Inception', returnPct: 12.5, benchmarkPct: null },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 97.99 },
    { kind: 'asset', label: 'MMI', weight: 1.86 },
    { kind: 'asset', label: 'NCA', weight: 0.15 },
    { kind: 'fnu', label: 'Equity', weight: 98, fuMin: 75, fuMax: 100 },
    { kind: 'fnu', label: 'Gsec / Debt', weight: 0, fuMin: 0, fuMax: 25 },
    { kind: 'fnu', label: 'MMI / Others', weight: 2, fuMin: 0, fuMax: 25 },
    { kind: 'sector', label: 'Financial service activities', weight: 26.26 },
    { kind: 'sector', label: 'Computer programming, consultancy', weight: 6.36 },
    { kind: 'sector', label: 'Manufacture of motor vehicles', weight: 6.3 },
  ],
  holdings: [
    { security: 'ICICI Bank Ltd.', weightPct: 6.26 },
    { security: 'Axis Bank Ltd.', weightPct: 3.41 },
    { security: 'HDFC Bank Ltd.', weightPct: 3.16 },
    { security: 'State Bank of India.', weightPct: 2.97 },
    { security: 'Larsen And Toubro Ltd.', weightPct: 2.93 },
    { security: 'Bharti Airtel Ltd.', weightPct: 2.9 },
    { security: 'Reliance Industries Ltd', weightPct: 2.76 },
    { security: 'Infosys Ltd.', weightPct: 2.64 },
    { security: 'Maruti Suzuki India Ltd', weightPct: 2.24 },
    { security: 'Mahindra & Mahindra Ltd', weightPct: 2.17 },
    { security: 'Others', weightPct: 66.54 },
    { security: 'MMI', weightPct: 1.86 },
    { security: 'NCA', weightPct: 0.15 },
  ],
}

// SBI Life — Equity Fund (sbi_ulip_may2026.pdf, as on 31 May 2026)
const SBI_EQUITY: ExtractedFund = {
  sfin: 'ULIF001100105EQUITY-FND111',
  name: 'Equity Fund',
  class: 'Individual',
  category: 'Equity',
  nav: 188.7691,
  inception: '10-Jan-05',
  benchmark: 'Nifty 50',
  manager: 'Mr. Gopikrishna Shenoy',
  aum: { equity: 75398.87, debt: 0.0, mmi: 1574.65, total: 76973.52 }, // INR Crore
  returns: [
    { period: '1M', returnPct: -1.35, benchmarkPct: -1.87 },
    { period: '6M', returnPct: -10.3, benchmarkPct: -10.13 },
    { period: '1Y', returnPct: -6.62, benchmarkPct: -4.86 },
    { period: '2Y', returnPct: 0.95, benchmarkPct: 2.23 },
    { period: '3Y', returnPct: 9.06, benchmarkPct: 8.31 },
    { period: 'Inception', returnPct: 14.71, benchmarkPct: 12.26 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 97.95 },
    { kind: 'asset', label: 'Debt', weight: 0.0 },
    { kind: 'asset', label: 'Money Market', weight: 2.05 },
    { kind: 'fnu', label: 'Equity', weight: 97.95, fuMin: 80, fuMax: 100 },
    { kind: 'fnu', label: 'Debt', weight: 0.0, fuMin: 0, fuMax: 20 },
    { kind: 'fnu', label: 'Money Market', weight: 2.05, fuMin: 0, fuMax: 20 },
    { kind: 'sector', label: 'Financial & insurance Activities', weight: 27.44 },
    { kind: 'sector', label: 'Computer Program, Consult & Related', weight: 7.89 },
    { kind: 'sector', label: 'Mfg Of Coke & Refined Petroleum Products', weight: 7.75 },
    { kind: 'sector', label: 'Mfg Of Pharm, Chemical & Botanical Products', weight: 5.31 },
    { kind: 'sector', label: 'Telecommunications', weight: 4.87 },
  ],
  holdings: [
    { security: 'ICICI Bank Ltd', weightPct: 8.51 },
    { security: 'HDFC Bank Ltd.', weightPct: 8.14 },
    { security: 'Reliance Industries Ltd.', weightPct: 7.75 },
    { security: 'Bharti Airtel Ltd.', weightPct: 4.87 },
    { security: 'Larsen & Toubro Ltd.', weightPct: 4.41 },
    { security: 'Infosys Limited', weightPct: 3.85 },
    { security: 'Axis Bank Ltd.', weightPct: 3.22 },
    { security: 'Mahindra & Mahindra Ltd.', weightPct: 2.75 },
    { security: 'Kotak Mahindra Bank Ltd.', weightPct: 2.71 },
    { security: 'Bajaj Finance Limited', weightPct: 2.18 },
    { security: 'Others', weightPct: 49.57 },
  ],
}

// PNB MetLife — Mid Cap Fund (pnb_june2026.pdf, as on 31 May 2026)
const PNB_MIDCAP: ExtractedFund = {
  sfin: 'ULIF02501/01/18MIDCAPFUND117',
  name: 'Mid Cap Fund',
  class: 'Individual',
  category: 'Equity - Mid Cap',
  nav: 45.5268,
  inception: '21-Mar-2018',
  benchmark: 'S&P BSE Midcap Index',
  manager: 'Amit Shah',
  aum: { equity: null, debt: null, mmi: null, total: 1576 }, // INR Crore (only total printed)
  returns: [
    { period: '1M', returnPct: 3.5, benchmarkPct: 1.6 },
    { period: '6M', returnPct: 5.5, benchmarkPct: -0.7 },
    { period: '1Y', returnPct: 11.8, benchmarkPct: 3.8 },
    { period: '2Y', returnPct: 9.9, benchmarkPct: 4.6 },
    { period: '3Y', returnPct: 24.8, benchmarkPct: 20.0 },
    { period: '5Y', returnPct: 22.3, benchmarkPct: 16.6 },
    { period: 'Inception', returnPct: 20.3, benchmarkPct: 14.0 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 97.8 },
    { kind: 'asset', label: 'Debt', weight: 0.0 },
    { kind: 'asset', label: 'Money Market', weight: 2.2 },
    { kind: 'fnu', label: 'Equities', weight: 97.8, fuMin: 60, fuMax: 100 },
    { kind: 'fnu', label: 'Debt', weight: 0.0, fuMin: 0, fuMax: 0 },
    { kind: 'fnu', label: 'Money Market', weight: 2.2, fuMin: 0, fuMax: 40 },
    { kind: 'sector', label: 'Financial and Insurance Activities', weight: 20.5 },
    { kind: 'sector', label: 'Mfg of Electrical Equipment', weight: 9.7 },
    { kind: 'sector', label: 'Infrastructure Related Activities', weight: 7.8 },
    { kind: 'sector', label: 'Computer Programming & Consultancy', weight: 5.9 },
  ],
  holdings: [
    { security: 'Samvardhana Motherson International Ltd', weightPct: 3.3 },
    { security: 'Federal Bank Ltd.', weightPct: 2.8 },
    { security: 'Multi Commodity Exchange of India Ltd.', weightPct: 2.4 },
    { security: 'Bharat Heavy Electricals Ltd.', weightPct: 2.3 },
    { security: 'BSE Limited', weightPct: 2.2 },
    { security: 'Syrma SGS Technology Limited', weightPct: 2.1 },
    { security: 'NMDC Ltd.', weightPct: 1.9 },
    { security: 'Oil India Ltd.', weightPct: 1.8 },
    { security: 'Ujjivan Small Finance Bank Limited', weightPct: 1.8 },
    { security: 'Power Finance Corpn. Ltd.', weightPct: 1.8 },
    { security: 'Others', weightPct: 75.5 },
    { security: 'Cash and Money Market', weightPct: 2.2 },
  ],
}

// Bharti AXA Life — Grow Money Fund (bhartiaxa_may2026.pdf, May 2026)
const BHARTI_GROWMONEY: ExtractedFund = {
  sfin: 'ULIF00221/08/2006EGROWMONEY130',
  name: 'Grow Money Fund',
  class: 'Individual',
  category: 'Equity',
  nav: 99.5948,
  inception: '24 Aug 2006',
  benchmark: 'Nifty 100',
  manager: null,
  aum: { equity: 19154.63, debt: null, mmi: 145.99, total: 19300.62 }, // INR Lakhs
  returns: [
    { period: '1M', returnPct: -0.48, benchmarkPct: -1.16 },
    { period: '6M', returnPct: -7.22, benchmarkPct: -7.96 },
    { period: '1Y', returnPct: -1.69, benchmarkPct: -2.9 },
    { period: '2Y', returnPct: 2.36, benchmarkPct: 2.3 },
    { period: '3Y', returnPct: 11.06, benchmarkPct: 10.11 },
    { period: '5Y', returnPct: 10.33, benchmarkPct: 9.27 },
    { period: 'Inception', returnPct: 12.33, benchmarkPct: 10.78 },
  ],
  allocations: [
    { kind: 'asset', label: 'Equity', weight: 99.24 },
    { kind: 'asset', label: 'Money Market/Cash', weight: 0.76 },
    { kind: 'fnu', label: 'Equity', weight: 99.24, fuMin: 80, fuMax: 100 },
    { kind: 'fnu', label: 'Money Market/Cash', weight: 0.76, fuMin: 0, fuMax: 40 },
    { kind: 'sector', label: 'Financial and Insurance Activities', weight: 23.83 },
    { kind: 'sector', label: 'Asset Management', weight: 9.39 },
    { kind: 'sector', label: 'Computer Programming, Consultancy', weight: 5.56 },
    { kind: 'sector', label: 'Manufacture of Coke and Refined Petroleum', weight: 5.4 },
  ],
  holdings: [
    { security: 'HDFC Bank Ltd', weightPct: 6.53 },
    { security: 'ICICI Bank Ltd', weightPct: 5.75 },
    { security: 'Reliance Industries Ltd', weightPct: 5.4 },
    { security: 'Bharti Airtel Ltd', weightPct: 4.47 },
    { security: 'Larsen & Toubro Ltd', weightPct: 4.36 },
    { security: 'Infosys Technologies Ltd', weightPct: 3.29 },
    { security: 'Axis Bank Ltd', weightPct: 2.45 },
    { security: 'Titan Industries Ltd', weightPct: 1.88 },
    { security: 'Zomato Limited', weightPct: 1.86 },
    { security: 'Kotak Mahindra Bank Ltd', weightPct: 1.85 },
    { security: 'Others', weightPct: 61.4 },
    { security: 'Money Market/Cash', weightPct: 0.76 },
  ],
}

const FIXTURES: Record<string, ExtractedFund[]> = {
  'hdfc|combined|2026-05': [HDFC_BLUECHIP, HDFC_OPPORTUNITIES],
  'tataaia|fund:largecap|2026-05': [TATA_LARGECAP],
  'kotak|combined|2026-05': [KOTAK_CLASSIC],
  'sbi|combined|2026-05': [SBI_EQUITY],
  'pnbmetlife|combined|2026-05': [PNB_MIDCAP],
  'bhartiaxa|combined|2026-05': [BHARTI_GROWMONEY],
}

/** Deterministic stand-in for a reference document, or [] if none is bundled. */
export function fixtureFor(adapterId: string, kind: string, month: string): ExtractedFund[] {
  return FIXTURES[`${adapterId}|${kind}|${month}`] ?? []
}
